load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Abseil LTS 20200923, Patch 2
http_archive(
    name = "com_google_absl",
    strip_prefix = "abseil-cpp-0f3bb466b868b523cf1dc9b2aaaed65c77b28862",
    urls = ["https://github.com/abseil/abseil-cpp/archive/0f3bb466b868b523cf1dc9b2aaaed65c77b28862.zip"],
)

# GoogleTest/GoogleMock framework. Used by most unit-tests.
http_archive(
    name = "com_google_googletest",
    sha256 = "9a8a166eb6a56c7b3d7b19dc2c946fe4778fd6f21c7a12368ad3b836d8f1be48",
    strip_prefix = "googletest-8567b09290fe402cf01923e2131c5635b8ed851b",
    urls = ["https://github.com/google/googletest/archive/8567b09290fe402cf01923e2131c5635b8ed851b.zip"],  # 2020-06-12T22:24:28Z
)

# Google benchmark.
http_archive(
    name = "com_github_google_benchmark",
    sha256 = "2a778d821997df7d8646c9c59b8edb9a573a6e04c534c01892a40aa524a7b68c",
    strip_prefix = "benchmark-bf585a2789e30585b4e3ce6baf11ef2750b54677",
    urls = ["https://github.com/google/benchmark/archive/bf585a2789e30585b4e3ce6baf11ef2750b54677.zip"],  # 2020-11-26T11:14:03Z
)

# C++ rules for Bazel.
http_archive(
    name = "rules_cc",
    sha256 = "9a446e9dd9c1bb180c86977a8dc1e9e659550ae732ae58bd2e8fd51e15b2c91d",
    strip_prefix = "rules_cc-262ebec3c2296296526740db4aefce68c80de7fa",
    urls = [
        "https://github.com/bazelbuild/rules_cc/archive/262ebec3c2296296526740db4aefce68c80de7fa.zip",
    ],
)

http_archive(
    name = "nlohmann_json_lib",
    build_file = "//third_party:nlohmann_json.BUILD",
    sha256 = "a17e33e6aa2b84dadc8fb3b6dd0e044c5b3b3c34e63baad9fb8136285586e8d4",
    strip_prefix = "json-01f6b2e74185371ee005379b1661be1780fc1344",
    urls = [
        "https://github.com/nlohmann/json/archive/01f6b2e74185371ee005379b1661be1780fc1344.zip",
    ],
)

http_archive(
    name = "com_github_jarro2783_cxxopts",
    build_file = "//third_party:jarro2783_cxxopts.BUILD",
    sha256 = "7021ce97f51a40f7fd3558da416ab6914b1d3f758ccf68a1e8734ad10b49b676",
    strip_prefix = "cxxopts-2.2.1",
    urls = [
        "https://github.com/jarro2783/cxxopts/archive/v2.2.1.zip",
    ],
)
